### ISSUE TITLE
Map right alt-gr key

### ISSUE THREAD

**Issue by ihewitt** [pymo/ppk_bluetooth#3]
Not really an issue, but just a quick addition didn't seem worth creating a fork and a PR just for this! Since the Palm is US layout, I found it useful to add a mapping at "Space2" for AltGr so I can use the InternationalUS layout to be able to type, for example "£" (Shift-AltGr-4)
€ etc.
[US International layout](https://en.wikipedia.org/wiki/QWERTY#US-International)

-#ifdef GERMAN_LAYOUT
+#if defined(GERMAN_LAYOUT)
   key_map[0b00110111] = '`';  // "Space 2"
+#elif defined(ALTGR_LAYOUT)
+  key_map[0b00110111] = KEY_RIGHT_ALT;  // "Space 2"
 #else
   key_map[0b00110111] = ' ';  // "Space 2"
 #endif

**Comment by pymo** [comment]
There is an actual German version of the PPK, and the AltGr is not on the Space key's location. The GERMAN_LAYOUT macro in my code is to support that keyboard. See the pic attached.

I guess your purpose is to type German characters using a US layout. You can make the change on your side, but I'd prefer not include it in the repo. Sorry...

Another suggestion: when you want to type a space with your right thumb, there is a high chance that it lands on the “Space/New” key due to its position, so mapping it to other keys may hurdle your typing. A better solution would be mapping the Done/Cancel key to AltGr (it was originally mapped to Insert). Then map Fn+ Del to be Insert.
![PXL_20230929_125035817](https://github.com/pymo/ppk_bluetooth/assets/5140323/1671cd60-47ec-4553-9a2f-285c3e6f3f09)

**Comment by ihewitt** [comment]
no worries, yes since there wasn't a UK version this is using a US layout keyboard so making use of the "US international" layout makes sense. As for the lcoation, on intl keyboards it's normal for Alt-Gr to be directly to the right of the spacebar so once you have been using the Alt-Gr combos it feels natural being there.
happy to keep the changes local.
I'm having some "lag/double key" issues at the moment to diagnosee, not sure whats going on.
